# Generated by Django 5.0.3 on 2024-03-22 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('venue', models.CharField(max_length=30)),
                ('date', models.DateField(default=None)),
                ('time', models.CharField(max_length=30)),
                ('desc', models.TextField(default=None)),
                ('img', models.ImageField(upload_to='event_img')),
                ('dept', models.CharField(choices=[('CSE', 'Computer Science and Engineering'), ('ECE', 'Electronics and Communication Engineering'), ('EEE', 'Electrical and Electronics Engineering'), ('ME', 'Mechanical Engineering'), ('CE', 'Civil Engineering'), (None, 'None')], default=None, max_length=30)),
                ('reg_link', models.URLField()),
            ],
        ),
    ]
