# Generated by Django 5.0.3 on 2024-03-26 11:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eventportalapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='reg_link',
        ),
    ]
