# Generated by Django 5.0.3 on 2024-03-26 12:23

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventportalapp', '0003_alter_event_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='url',
            field=models.URLField(max_length=100, null=True, validators=[django.core.validators.URLValidator()]),
        ),
    ]
