# Generated by Django 5.0.3 on 2024-03-31 17:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventportalapp', '0004_event_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='Competition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('venue', models.CharField(max_length=30)),
                ('date', models.DateField()),
                ('time', models.CharField(max_length=30)),
                ('desc', models.TextField(default=None)),
                ('img', models.ImageField(upload_to='competition_img')),
                ('dept', models.CharField(choices=[('CSE', 'Computer Science and Engineering'), ('ECE', 'Electronics and Communication Engineering'), ('EEE', 'Electrical and Electronics Engineering'), ('ME', 'Mechanical Engineering'), ('CE', 'Civil Engineering'), (None, 'None')], default=None, max_length=30)),
                ('url', models.URLField(max_length=100, null=True, validators=[django.core.validators.URLValidator()])),
            ],
        ),
    ]
